### ISSUE TITLE
windSpeed not handled properly when None

### ISSUE THREAD

**Issue by tommyjlong** [tommyjlong/wral_weather#3]
Log:
```
Update for weather.wral_weather fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/wral_weather/weather.py", line 183, in async_update
    await self.wral.update_observation_and_forecast()
  File "/config/custom_components/wral_weather/wral_weather.py", line 370, in update_observation_and_forecast
    self.curr_dict = parse_current_conditions(current_json)
  File "/config/custom_components/wral_weather/wral_weather.py", line 185, in parse_current_conditions
    curr_dict['current_wind_speed'] =  int(curr_json['windSpeed'])
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by tommyjlong** [comment]
Hopefully fixed by v0.2.2
